title = "FaceMan's Blog"
baseURL = "https://blog.faceman.cn"
theme = "gohugo-theme-ananke"
resourceDir = "../resources"
defaultContentLanguage = "zh"
sectionPagesMenu = "main"
enableRobotsTXT = true

show_reading_time = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 5

[languages.zh]
contentDir = "content/zh"
languageCode = 'zh-CN'
weight = 1
title = "FaceMan's Blog"

#[languages.en]
#contentDir = "content/en"
#languageCode = 'en-US'
#weight = 1
#title = "FaceMan's Blog En"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "faceman"
favicon = ""
site_logo = ""
description = "从0开始，直到1。"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 5

[params.ananke.social.follow]
networks = [
  "github"
]

[params.ananke.social.share]
networks = [
  "email"
]

[[ananke.social.networks]]
slug = "github"
label = "GitHub"
color = "#6cc644"
profile = "https://github.com/faceman0814"
icon = "github" # font awesome brand icon name

[[ananke.social.networks]]
slug = "email"
label = "Email"
profile = false
icon = "envelope" # font awesome free icon name
link = "mailto:1002784867@qq.com"

[services.disqus]
  shortname = "FaceMan"
  # shortname = "faceman0814.github.io"